apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/techarx/argodemo.git
    targetRevision: HEAD
    path: app-helm
    helm:
      values: |
        image:
          tag: "1.16.0"
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: example-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      
