apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/techarx/argodemo.git
    targetRevision: HEAD
    path: app-helm
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: app-helm
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
